spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

  data.rest:
    base-path: /api
    detection-strategy: annotated