spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true