debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.example.forum: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql.init.mode: always     # data.sql

  data.rest:
    base-path: /api
    detection-strategy: annotated

  thymeleaf3:
    decoupled-logic: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# HTTPs 설정
server:
  ssl:
    key-store: classpath:kanu-keystore.p12
    key-store-type: PKCS12
    key-store-password: 8452994ash!
    key-alias: kanu-keystore

---

spring:

  config.activate.on-profile: testdb

  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

  sql.init.mode: always
